### ISSUE TITLE
printf error

### ISSUE THREAD

**Issue by marchoftheb** [amarjeetanandsingh/jps_stat#1]
Hi,
great script. But if I execute the script I get this error:
`./jpsstat.sh: line 89: printf: 234.637: invalid number
./jpsstat.sh: line 89: printf: 234.637: invalid number
./jpsstat.sh: line 89: printf: 1.1: invalid number
`
I found the issue in the printf command where %f has issues to work with decimal numbers. Therefore I modified a few lines:
```
   MEMORY_T=$(jstat -gc $pid | tail -n 1 | awk '{split($0,a," "); sum=a[3]+a[4]+a[6]+a[8]; mb=sum/1024; print mb}')
        MEMORY=${MEMORY_T%.*}
```
and 
`printf "%-6s %-44s %8.2f %8.2f  %5.1s\n" $pid ${curr_pid_name["$pid"]} $MEMORY ${curr_pid_max["$pid"]} $cpuuse | sort`

It's just a workaround. Hope that helps.

Regards
Marcho

**Comment by amarjeetanandsingh** [comment]
Hi Marcho.

Thank you for pointing the issue. I have used your suggestion to fix the code. The decimal values in the output is truncated now.
