### ISSUE TITLE
Docker sh support

### ISSUE THREAD

**Issue by cdalexndr** [amarjeetanandsingh/jps_stat#12]
../../jpsstat.sh: line 98: jps: command not found

Running inside a docker container.
Current working directory is `jdk/bin`, and jps is present.
```
sh-4.4# ls | grep jps
jps
```

**Comment by cdalexndr** [comment]
After running: `export PATH=$PATH:.` I get valid line followed by error:
`../../jpsstat.sh: line 104: tput: command not found`

**Comment by amarjeetanandsingh** [comment]
Hi @cdalexndr 
`../../jpsstat.sh: line 104: tput: command not found` says `tput` is not installed. `tput` is used in the script to push the curser  backwards to write the new values on terminal.

Most probably you are using linux distribution like **alpine** that doesn't come with `tput` pre-installed. 
Not sure about your distribution, but taking **alpine** as example,  adding `RUN apk add ncurses` in your Dockerfile can help. All you have to do is to install the `tput` in your environment.
