### ISSUE TITLE
Crashes on Linux with sytax error; seems to haven't been tested 

### ISSUE THREAD

**Issue by MathiasZaja** [amarjeetanandsingh/jps_stat#2]
Wrong repository or published wihout being teste ?
![jpsstat_ch](https://user-images.githubusercontent.com/19735583/31195339-4cc846ea-a94a-11e7-8134-3df9ecf782d5.png)

**Comment by amarjeetanandsingh** [comment]
Looks like you are getting error on associative array declaration, which needs bash version  >= 4.  What is your bash version?

**Comment by amarjeetanandsingh** [comment]
since bash >= 4 is required for associative array declaration, it won't work in lower version of bash. And its working properly on bash >=4, so i am clothing this issue.

**Comment by MathiasZaja** [comment]
As reported it's not workiong with bash 4.3.
      But you can do what the f**k you want with your piece of software.
    
    Le 06.10.2017 à 20:50, Amarjeet Anand a
      écrit :
    
    
      since bash >= 4 is required for associative array
        declaration, it won't work in lower version of bash. And its
        working properly on bash >=4, so i am clothing this issue.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amarjeetanandsingh/jps_stat","title":"amarjeetanandsingh/jps_stat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/amarjeetanandsingh/jps_stat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amarjeetanandsingh in #2: since bash \u003e= 4 is required for associative array declaration, it won't work in lower version of bash. And its working properly on bash \u003e=4, so i am clothing this issue. "}],"action":{"name":"View Issue","url":"https://github.com/amarjeetanandsingh/jps_stat/issues/2#issuecomment-334839924"}}}
    
    
    -- 
      Mathias Zajaczkowski
      Ubik S.A.
      Chemin du Signal 22
      1296 Coppet
      (+) 41 22 960 03 91
      mathias.zajaczkowski@ubik.ch

**Comment by amarjeetanandsingh** [comment]
But you didn't mentioned your bash version earlier. It's ok. Could you please mention your environment details, and how can i reproduce that?

**Comment by MathiasZaja** [comment]
Sur, I did; with screen shot.
      See below
    
    Hi,
      
      Apparently my bash version is 4.3.30 thus >= 4.
      
    
    
    
    
    Regards
    Le 07.10.2017 à 11:21, Amarjeet Anand a
      écrit :
    
    
      But you didn't mentioned your bash version earlier. It's ok.
        Could you please mention your environment details, 
    
    What details do you need ?
    
      and how can i reproduce that?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amarjeetanandsingh/jps_stat","title":"amarjeetanandsingh/jps_stat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/amarjeetanandsingh/jps_stat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amarjeetanandsingh in #2: But you didn't mentioned your bash version earlier. It's ok. Could you please mention your environment details, and how can i reproduce that?"}],"action":{"name":"View Issue","url":"https://github.com/amarjeetanandsingh/jps_stat/issues/2#issuecomment-334922219"}}}
    
    
    -- 
      Mathias Zajaczkowski
      Ubik S.A.
      Chemin du Signal 22
      1296 Coppet
      (+) 41 22 960 03 91
      mathias.zajaczkowski@ubik.ch

**Comment by amarjeetanandsingh** [comment]
Ok...
One possible solution to your problem is that you may be running the script as ` sh jpsstat.sh `  which executes the script as ` sh ` and not as ` bash ` . And since associative array is a bash thing, you are getting the syntax error.

As mentioned on [Readme](https://github.com/amarjeetanandsingh/jps_stat#how-to-use) page, running with ` ./jpsstat.sh ` executes the script as ` /bin/bash `  as in first line after ` !# ` 

Let me know if it solves your problem.
