### ISSUE TITLE
Heap Memory and RAM

### ISSUE THREAD

**Issue by jsand66** [amarjeetanandsingh/jps_stat#7]
I see the RAM memory is lesser than Heap Memory when ran the script in a docker container. Is RAM memory is calculated by excluding heap? .Because heap memory should be a part of RAM right ?

**Comment by amarjeetanandsingh** [comment]
Hi @jsand66 
Thanks for using jps_stat

As mentioned in the [jps_stat doc](https://github.com/amarjeetanandsingh/jps_stat#script-details),  RAM is calculated using the `rss` field of the output of `/proc/<pid>/statm` command. **Man** page of [proc](http://man7.org/linux/man-pages/man5/proc.5.html) command says -

> Resident Set Size: number of pages the process has
> in real memory.  This is just the pages which count
> toward text, data, or stack space.  This does not
> include pages which have not been demand-loaded in,
> or which are swapped out.

So it is possible that the pages are swapped out of ram at the moment this script ran resulting in lesser ram than heap.


Hope that helps.

**Comment by d01mf** [comment]
I see the same thing and from what I can see the value from statm is never converted from pages to kb. One should multiply by the page size (normally 4k). 
There's just divide by 1024 in the code to convert to Mb, so the value is off by a factor of 4
